// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsnZIJ687cOn_lvQkhHtxDAV8GauyWyzY',
    appId: '1:442166278518:android:68ed5882c0f2171a34a257',
    messagingSenderId: '442166278518',
    projectId: 'mangacloud-1fcba',
    storageBucket: 'mangacloud-1fcba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDadjlEhafpf2-Iu3LtAh4Awke9pkNOM_U',
    appId: '1:442166278518:ios:f1f8de85a191275e34a257',
    messagingSenderId: '442166278518',
    projectId: 'mangacloud-1fcba',
    storageBucket: 'mangacloud-1fcba.appspot.com',
    iosBundleId: 'com.saveriogramegna.mangacloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcTI2cImwX0gx3nanvgs6ThTL5hPKHjAM',
    appId: '1:442166278518:web:e18ba88b6df6e55d34a257',
    messagingSenderId: '442166278518',
    projectId: 'mangacloud-1fcba',
    authDomain: 'mangacloud-1fcba.firebaseapp.com',
    storageBucket: 'mangacloud-1fcba.appspot.com',
    measurementId: 'G-HDTEC04027',
  );
}
